const cartTypes = {
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    DELETE_ITEM:'DELETE_ITEM',
    DECREASE_ITEM:'DECREASE_ITEM',
    INCREASE_ITEM:'INCREASE_ITEM'
}
export default cartTypes